# Generated by Django 4.0.8 on 2022-10-16 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('divice', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NameItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
    ]
