# Generated by Django 4.0.8 on 2022-10-16 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('divice', '0002_nameitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imageitem',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
