# Generated by Django 4.1.2 on 2022-10-16 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('divice', '0003_alter_imageitem_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
            ],
        ),
        migrations.RenameModel(
            old_name='ImageItem',
            new_name='Image',
        ),
        migrations.RenameModel(
            old_name='NameItem',
            new_name='Name',
        ),
    ]
