# Generated by Django 4.0.8 on 2022-10-16 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('divice', '0004_item_rename_imageitem_image_rename_nameitem_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='filename',
            field=models.CharField(default='', max_length=100),
        ),
    ]
